### PR TITLE
Add aalborg artwork

### PR DESCRIPTION
**Pull request by AllanHoejgaardJensen**
### added artwork from aalborg.

Please note that I added 3 extra files besides the original background _aalborg.png_.
These are:
- a frontpage for events used in a google slide template set for the meetup in aalborg and announced on meetup.com _aalborg-meetup.png_. 
- two editions of frontpage for the slidedeck for a meetup on location, one of these with hashtags only _aalborg-ht.png_, the other including slack info as well _aalborg-hts.png_.

### CODE REVIEW

**Review by luxas — APPROVED** [review]
Awesome, thanks!
Is it possible to automate the the generation of the `-*` files somehow, or did you do it manually?

Before merging, can you add the coordinates to the json file so others might reproduce the image you created?

**Comment by kaspernissen** [comment]
Looks good, @AllanHoejgaardJensen ! As Lucas suggest, could you please add the coordinates to the `places.json` file to be able to reproduce this later on. Also, how did you create the rest - and could we have the generator doing this?

**Comment by AllanHoejgaardJensen** [comment]
added location, did not automate the frontpages, although that is a good idea.

**Comment by luxas** [comment]
Awesome, thanks!

**Pull request merged**
